name = "mina-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
keep_vars = true

[vars]
ENVIRONMENT = "production"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
